// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwrlxxrvuovgbotcdkdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3cmx4eHJ2dW92Z2JvdGNka2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDc1NzAsImV4cCI6MjA2MTI4MzU3MH0.YXoq1ohec6mL4l4_dwLZJvgrzcoiEb0qQjEh8cOsRkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});